makhbazti_dbt:
  target: dev
  outputs:
    dev:
      dbname: "{{ env_var('DBT_DBNAME', 'default_db_name') }}"  # Use 'default_db_name' if DBT_DBNAME is not set
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      pass: "{{ env_var('DBT_PASSWORD', 'your_password') }}"
      port: "{{ env_var('DBT_PORT', '5432') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'default_schema') }}"
      threads: 10
      type: postgres
      user: "{{ env_var('DBT_USER', 'postgres') }}"
