makhbazti_modeling:
  outputs:
    dev:
      dbname: makhbazti_wh
      host: olap_wh
      pass: secret
      port: 5432
      schema: sales_mart
      threads: 4
      type: postgres
      user: postgres