<<<<<<< HEAD
# put your secret values and credentials here. do not share this file and do not push it to github
=======
>>>>>>> origin/main
[sources.mongodb]
connection_url = "mongodb://localhost:27017/makhbazti_store1" # please set me up!

[destination.postgres.credentials]
database = "final_test" # please set me up!
password = "secret" # please set me up!
username = "postgres" # please set me up!
host = "localhost" # please set me up!
port = 5432
connect_timeout = 15
