<<<<<<< HEAD
# put your secret values and credentials here. do not share this file and do not push it to github
=======
>>>>>>> origin/main
[sources.mongodb]
connection_url = "${MONGODB_CONNECTION_URL}" # please set me up!

[destination.postgres.credentials]
database = "${POSTGRES_DB}" # please set me up!
password = "${POSTGRES_PASSWORD}" # please set me up!
username = "${POSTGRES_USER}" # please set me up!
host = "${POSTGRES_HOST}" # please set me up!
port = ${POSTGRES_PORT}
connect_timeout = ${POSTGRES_CONNECT_TIMEOUT}