name: Build and Deploy ELT Pipeline

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: read
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for building images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true  # Set to true to push the image to GHCR
          tags: ghcr.io/${{ github.repository_owner | toLower }} /makhbazti_elt:latest

      # Step 5: Optional - Deploy the Docker container (if applicable)
      - name: Deploy to Environment
        run: |
          echo "Deploying the Docker image..."
          # Add your deployment commands here, if necessary
